### ISSUE TITLE
Add to MELPA?

### ISSUE THREAD

**Issue by manuel-uberti** [wasamasa/punpun-theme#1]
Not a bug or an issue, but would you consider adding it to MELPA? 

Speaking as a Solarized Light user, I love the simplicity of your theme.

**Comment by wasamasa** [comment]
First of all, thanks, I didn't expect my followers to pick it up that quickly :D

I'm still exploring how the dark version should look, trying out variations on the basic faces and settling for the colour shades, so that's why I didn't add it to MELPA yet.  To ensure it won't happen by accident either, I intentionally "forgot" including a package header.  Once I believe it's ready for inclusion, I'll update the README and package header.

**Comment by manuel-uberti** [comment]
Cool, thank you. I'll follow the development closely.

**Comment by wasamasa** [comment]
OK, I think it's good to go!

**Comment by manuel-uberti** [comment]
Beautiful! Thank you very much.
